---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluefin-hypr
# description will be included in the image's metadata
description: bluefin w/o crap

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/yalter/niri/repo/fedora-%OS_VERSION%/yalter-niri-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/pgdev/ghostty/repo/fedora-%OS_VERSION%/pgdev-ghostty-fedora-%OS_VERSION%.repo
    install:
      - niri
      - micro
      - ghostty
      - hyprland
      - waypaper
      - hyprlock
      - hypridle
      - waybar
      # - starship
    remove:
      
      - gnome-tour

  - type: fonts
    fonts:
      nerd-fonts:
        - Iosevka
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
        - google-noto-emoji-fonts

      
- type: default-flatpaks
  configurations:
    - scope: user
      repo:
        # you can override the title to make inclusion of both system and user repos clearer
        title: Flathub (user)
    - notify: true
      scope: system
      repo:
        title: Flathub (system)
      install: # system flatpaks we want all users to have and not remove
        - org.mozilla.firefox
  

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

